import pyautogui as pg
from time import sleep  # что под # для открытия в косольке, здесь оно только мешает
import os

os.system('cls' if os.name == 'nt' else 'clear')
print ("Шутник v0.5")
print("ШЯ ВСЁ БУДЕТ!")
sleep(0.2)

pg.hotkey("winleft")
pg.moveTo(1743, 1060, 0.01)
pg.leftClick()
pg.moveTo(1746, 980, 0.01)
pg.leftClick()
sleep(0.2)
pg.typewrite("firefox\n", 0.01)
sleep(0.2)
pg.typewrite("https://www.anekdot.ru/random/anekdot\n", 0.01)
pg.hotkey("winleft", "up")
sleep(0.3)
pg.moveTo(300, 400, 0.1)
sleep(0.1)
pg.drag(300, 600, 0.1, button="left")
pg.hotkey("ctrl", "c")
pg.hotkey("alt", "f4")
sleep(0.1)
pg.hotkey("winleft")
pg.typewrite("notepad\n", 0.01)
sleep(0.1)
pg.hotkey("ctrl", "v")
pg.hotkey("enter")
pg.typewrite("AVE SHYTNIK!")
print ("шутник свою работу сделал")